name: "README"
output_dir: "docs"
navbar:
  title: "README"
  left:
  - text: "Home"
   href: README.html
  - text: "CPFMove Introduction"
   href: README.html
output:
  html_document:
  theme: jekyll-theme-dinky
