name: "README"
output_dir: "docs"
navbar:
  title: "Introduction"
  left:
  - text: "Home"
   href: CPFReadme.html
  - text: "CPF Introduction"
   href: README.html
output:
  html_document:
  theme: jekyll-theme-dinky
